# deploy mongodb
# User: root
# Password: Aa123456

version: '3.8'
services: 
  mongodb:
    image: mongo
    #restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  # mongo-express:
  #   image: mongo-mongo-express
  #   #restart: always
  #   ports: 
  #     -8081:8081
  #   environment: 
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: Aa123456
  