# deploy mongodb
# User: root
# Password: Aa123456

version: '3.8'
services: 
  mongodb:
    image: mongo:4.4.13
    #restart: always
    ports:
      - 27017:27017
    volumes: 
      # - ./workdir/configdb:/data/configdb
      - ./data:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  